import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, } from "@/components/ui/dropdown-menu";
import { NavigationMenu, NavigationMenuItem, NavigationMenuList } from "@/components/ui/navigation-menu";
import useAuthStore from "@/store/authStore";
import { ChevronDown } from "lucide-react";
import { Link } from "react-router-dom";
import { Badge } from "../ui/badge";
export const Navbar = () => {
    const { isAuthenticated, user, logout } = useAuthStore();
    return (_jsx("header", { className: "bg-white shadow", children: _jsxs("div", { className: "container mx-auto flex items-center justify-between p-4", children: [_jsx(Link, { to: "/", className: "flex items-center space-x-2 focus:outline-none", children: _jsx("div", { className: "text-2xl font-bold text-gray-800", children: "VidSpark" }) }), _jsx(NavigationMenu, { children: _jsxs(NavigationMenuList, { className: "flex space-x-4", children: [_jsx(NavigationMenuItem, { children: _jsx(Link, { to: "/", className: "hover:text-blue-600", children: "Home" }) }), _jsx(NavigationMenuItem, { children: _jsx(Link, { to: "/about", className: "hover:text-blue-600", children: "About" }) }), _jsx(NavigationMenuItem, { children: _jsx(Link, { to: "/contact", className: "hover:text-blue-600", children: "Contact" }) })] }) }), _jsx("div", { className: "flex space-x-2", children: isAuthenticated ? (_jsxs(_Fragment, { children: [_jsxs(DropdownMenu, { children: [_jsxs(DropdownMenuTrigger, { className: "flex items-center space-x-2 focus:outline-none", children: [_jsx("img", { src: user?.profileImage || "/default-avatar.jpg", alt: "Profile", className: "w-10 h-10 rounded-full border" }), _jsx(ChevronDown, { className: "w-4 h-4 text-gray-600" })] }), _jsxs(DropdownMenuContent, { align: "end", className: "bg-white shadow-lg rounded-md p-1 w-auto", children: [_jsx(DropdownMenuItem, { children: _jsx("div", { className: "px-3 py-1 text-sm text-gray-600", children: user?.email }) }), _jsx(Link, { to: "/profile", className: "block px-3 py-1 text-gray-800 hover:bg-gray-100 rounded-md", children: _jsx(DropdownMenuItem, { children: "Profile" }) }), _jsx(DropdownMenuItem, { children: _jsx("button", { onClick: logout, className: "w-full text-left  px-3 py-1 text-red-600 hover:bg-gray-100 rounded-md", children: "Logout" }) })] })] }), _jsxs(Badge, { color: "red", variant: "outline", children: [" Credits:", " ", " ", " " + (user?.totalCredits || 0)] })] })) : (_jsxs("div", { className: "flex space-x-2", children: [_jsx(Button, { variant: "outline", asChild: true, children: _jsx("a", { href: "/login", children: "Login" }) }), _jsx(Button, { variant: "default", asChild: true, children: _jsx("a", { href: "/register", children: "Sign Up" }) })] })) })] }) }));
};
